version: 2.1

orbs:
  maven: circleci/maven@0.0.12

workflows:
  maven_test:
    jobs:
      build:
        docker:
           - image: selenium/standalone-chrome:3.1.0
        steps:   
           run: - maven/test # checkout, build, test, and upload test results
